/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  device_home: () => import("@/views/device/home/index.vue"),
  "device_task-detail": () => import("@/views/device/task-detail/index.vue"),
  device_task: () => import("@/views/device/task/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_home: () => import("@/views/log/home/index.vue"),
  network_home: () => import("@/views/network/home/index.vue"),
  network_link: () => import("@/views/network/link/index.vue"),
  network_node: () => import("@/views/network/node/index.vue"),
  user_create: () => import("@/views/user/create/index.vue"),
  user_home: () => import("@/views/user/home/index.vue"),
};
