/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'device',
    path: '/device',
    component: 'layout.base',
    meta: {
      title: 'device',
      i18nKey: 'route.device',
      order: 3,
      icon: 'mdi:mobile-devices'
    },
    children: [
      {
        name: 'device_home',
        path: '/device/home',
        component: 'view.device_home',
        meta: {
          title: 'device_home',
          i18nKey: 'route.device_home'
        }
      },
      {
        name: 'device_task',
        path: '/device/task',
        component: 'view.device_task',
        meta: {
          title: 'device_task',
          i18nKey: 'route.device_task'
        }
      },
      {
        name: 'device_task-detail',
        path: '/device/task-detail',
        component: 'view.device_task-detail',
        meta: {
          title: 'device_task-detail',
          i18nKey: 'route.device_task-detail',
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      order: 3,
      icon: 'mdi:comment-bookmark-outline'
    },
    children: [
      {
        name: 'log_home',
        path: '/log/home',
        component: 'view.log_home',
        meta: {
          title: 'log_home',
          i18nKey: 'route.log_home'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'network',
    path: '/network',
    component: 'layout.base',
    meta: {
      title: 'network',
      i18nKey: 'route.network',
      icon: 'mdi:graph',
      order: 2
    },
    children: [
      {
        name: 'network_home',
        path: '/network/home',
        component: 'view.network_home',
        meta: {
          title: 'network_home',
          i18nKey: 'route.network_home'
        }
      },
      {
        name: 'network_link',
        path: '/network/link',
        component: 'view.network_link',
        meta: {
          title: 'network_link',
          i18nKey: 'route.network_link'
        }
      },
      {
        name: 'network_node',
        path: '/network/node',
        component: 'view.network_node',
        meta: {
          title: 'network_node',
          i18nKey: 'route.network_node'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:user',
      order: 4
    },
    children: [
      {
        name: 'user_create',
        path: '/user/create',
        component: 'view.user_create',
        meta: {
          title: 'user_create',
          i18nKey: 'route.user_create'
        }
      },
      {
        name: 'user_home',
        path: '/user/home',
        component: 'view.user_home',
        meta: {
          title: 'user_home',
          i18nKey: 'route.user_home'
        }
      }
    ]
  }
];
